---
- name: set hostname
  hostname: name=cartographer

- name: install cartographer
  git: repo=https://github.com/kislyuk/cartographer
       dest=/srv/cartographer

- name: load cartographer database
  shell: echo "Will load DB"