---
- name: install base requirements
  apt: name={{item}} state=installed
  with_items:
    - tmux
    - screen
    - keychain
    - nginx
    - htop
    - python-dev
    - python-pip
    - python-virtualenv
    - python-openssl
    - libsnappy-dev
    - git
    - curl
    - pandoc
    - lxc
    - ufw
    - bridge-utils
    - whois
    - ntp
    - build-essential
    - cryptsetup-bin
    - mdadm
    - btrfs-tools
    - unzip
    - uwsgi
    - colordiff
    - pydf
    - xfsprogs

- name: install bashrc
  sudo: no
  template: src=bashrc dest=~/.bashrc

- name: format ephemeral storage
  script: assemble_ephemeral_RAID

- name: mount ephemeral storage
  mount: name=/mnt/ephemeral-raid src='LABEL=ephemeral-raid' state=mounted fstype=auto

- name: remove postfix
  apt: name=postfix state=absent

- name: remove whoopsie
  apt: name=whoopsie state=absent
