---
- name: install base requirements
  apt: name={{item}} state=installed
  with_items:
    - tmux
    - screen
    - keychain
    - nginx
    - htop
    - tree
    - colordiff
    - libsnappy-dev
    - git
    - curl
    - pandoc
    - lxc
    - ufw
    - bridge-utils
    - whois
    - ntp
    - build-essential
    - cryptsetup-bin
    - mdadm
    - btrfs-tools
    - unzip
    - uwsgi
    - colordiff
    - pydf
    - xfsprogs
    - mosh
    - emacs
    - nmap
    - cmake
    - flex
    - bison
    - libpam0g-dev
    - zlib1g-dev
    - libbz2-dev
    - libfuse-dev
    - libfuse2
    - fuse-utils
    - python-dev
    - python-pip
    - python-openssl
    - python-crypto
    - python-numpy
    - python-scipy
    - python-pyxattr
    - python-fuse
    - uwsgi-plugins-all
    - attr

- name: install virtualenv
  command: pip install --upgrade virtualenv

- name: install python3.3 PPA
  apt_repository: repo='ppa:fkrull/deadsnakes'

- name: install python3.3
  apt: name={{item}} state=installed
  with_items:
    - python3.3
    - python3.3-dev

- name: set python3.3 as the default python3
  command: ln -sf /usr/bin/python3.3 /usr/bin/python3

- name: install node.js
  include: install_nodejs.yml

- name: install bashrc
  sudo: no
  template: src=bashrc dest=~/.bashrc

- name: format ephemeral storage
  script: assemble_ephemeral_RAID

- name: mount ephemeral storage
  mount: name=/mnt/ephemeral-raid src='LABEL=ephemeral-raid' state=mounted fstype=auto

- name: remove postfix
  apt: name=postfix state=absent

- name: remove whoopsie
  apt: name=whoopsie state=absent
